### ISSUE TITLE
Icon Request [name of coin]

### ISSUE THREAD

**Issue by Benny2102** [GH2user/hass-crypto-icons#2]
Zilliqa (ZIL), Gala (GALA) please if possible. Thanks for the work so far.

**Comment by GH2user** [comment]
Hi Benny2102,
I'll see if I can fit it in over the weekend.

**Comment by GH2user** [comment]
Hi Benny2102,
Took a bit longer but these are added now in v1-3-0.
Please update the javascript file on your system and use CTRL-F5 to refresh the cached icons.
